// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataEntities
{
    public partial class CatSubCategoria
    {
        public CatSubCategoria()
        {
            TblProducto = new HashSet<TblProducto>();
        }

        public int Id { get; set; }
        public int? IdCategoria { get; set; }
        public string Nombre { get; set; }
        public string Estado { get; set; }

        public virtual CatCategoria IdCategoriaNavigation { get; set; }
        public virtual ICollection<TblProducto> TblProducto { get; set; }
    }
}