// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataEntities
{
    public partial class RegistroPersona
    {
        public RegistroPersona()
        {
            RolesUsuario = new HashSet<RolesUsuario>();
            SesionUsuarios = new HashSet<SesionUsuarios>();
        }

        public int IdRegistroPersona { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }

        public virtual ICollection<RolesUsuario> RolesUsuario { get; set; }
        public virtual ICollection<SesionUsuarios> SesionUsuarios { get; set; }
    }
}