// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataEntities
{
    public partial class Roles
    {
        public Roles()
        {
            RolesUsuario = new HashSet<RolesUsuario>();
        }

        public int IdRol { get; set; }
        public string Rol { get; set; }
        public string DescripcionRoles { get; set; }

        public virtual ICollection<RolesUsuario> RolesUsuario { get; set; }
    }
}