// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataEntities
{
    public partial class RolesUsuario
    {
        public int IdRolesUsuario { get; set; }
        public int IdRegistroPersona { get; set; }
        public int? IdRol { get; set; }

        public virtual RegistroPersona IdRegistroPersonaNavigation { get; set; }
        public virtual Roles IdRolNavigation { get; set; }
    }
}