// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataEntities
{
    public partial class SesionUsuarios
    {
        public SesionUsuarios()
        {
            TblCompras = new HashSet<TblCompras>();
            TblConfiguracion = new HashSet<TblConfiguracion>();
            TblMovimientoProductos = new HashSet<TblMovimientoProductos>();
            TblVentas = new HashSet<TblVentas>();
        }

        public int IdUsuario { get; set; }
        public int IdRegistroPersona { get; set; }
        public string Email { get; set; }
        public string Contraseña { get; set; }

        public virtual RegistroPersona IdRegistroPersonaNavigation { get; set; }
        public virtual ICollection<TblCompras> TblCompras { get; set; }
        public virtual ICollection<TblConfiguracion> TblConfiguracion { get; set; }
        public virtual ICollection<TblMovimientoProductos> TblMovimientoProductos { get; set; }
        public virtual ICollection<TblVentas> TblVentas { get; set; }
    }
}