// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataEntities
{
    public partial class TblAlmacenProducto
    {
        public TblAlmacenProducto()
        {
            TblDetalleVenta = new HashSet<TblDetalleVenta>();
            TblProductoDañado = new HashSet<TblProductoDañado>();
        }

        public int IdAlmacenProducto { get; set; }
        public int? IdAlmacen { get; set; }
        public int? IdProducto { get; set; }
        public int? IdMarca { get; set; }
        public int? IdTalla { get; set; }
        public int? IdColor { get; set; }
        public string NombreProducto { get; set; }
        public string DescripcionArticulo { get; set; }
        public decimal? PrecioUnitario { get; set; }
        public int? Cantidad { get; set; }
        public decimal? PrecioVenta { get; set; }
        public decimal? Unidades { get; set; }
        public decimal? UnidadesTotales { get; set; }

        public virtual CatAlmacen IdAlmacenNavigation { get; set; }
        public virtual CatColor IdColorNavigation { get; set; }
        public virtual CatMarca IdMarcaNavigation { get; set; }
        public virtual TblProducto IdProductoNavigation { get; set; }
        public virtual CatTalla IdTallaNavigation { get; set; }
        public virtual ICollection<TblDetalleVenta> TblDetalleVenta { get; set; }
        public virtual ICollection<TblProductoDañado> TblProductoDañado { get; set; }
    }
}