// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataEntities
{
    public partial class TblConfiguracion
    {
        public int IdConfiguracion { get; set; }
        public int? IdUsuario { get; set; }
        public byte[] LogoEmpresa { get; set; }
        public string NombreEmpresa { get; set; }
        public string DireccionEmpresa { get; set; }
        public string EncabezadoFactura { get; set; }

        public virtual SesionUsuarios IdUsuarioNavigation { get; set; }
    }
}