// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataEntities
{
    public partial class TblMovimientoProductos
    {
        public int IdMovimientoProducto { get; set; }
        public int IdTipoMovimiento { get; set; }
        public int? IdUsuario { get; set; }
        public int? IdProducto { get; set; }
        public DateTime? FechaDeMovimiento { get; set; }
        public string CodigoArticulo { get; set; }
        public int? Cantidad { get; set; }
        public string DescripcionMovimientoProducto { get; set; }

        public virtual TblProducto IdProductoNavigation { get; set; }
        public virtual TblTipoMovimiento IdTipoMovimientoNavigation { get; set; }
        public virtual SesionUsuarios IdUsuarioNavigation { get; set; }
    }
}