// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataEntities
{
    public partial class TblProducto
    {
        public TblProducto()
        {
            TblAlmacenProducto = new HashSet<TblAlmacenProducto>();
            TblDetalleCompra = new HashSet<TblDetalleCompra>();
            TblDevoluciones = new HashSet<TblDevoluciones>();
            TblMovimientoProductos = new HashSet<TblMovimientoProductos>();
        }

        public int Id { get; set; }
        public string NombreProducto { get; set; }
        public string Descripcion { get; set; }
        public int? IdSubCategoria { get; set; }
        public string Estado { get; set; }

        public virtual CatSubCategoria IdSubCategoriaNavigation { get; set; }
        public virtual ICollection<TblAlmacenProducto> TblAlmacenProducto { get; set; }
        public virtual ICollection<TblDetalleCompra> TblDetalleCompra { get; set; }
        public virtual ICollection<TblDevoluciones> TblDevoluciones { get; set; }
        public virtual ICollection<TblMovimientoProductos> TblMovimientoProductos { get; set; }
    }
}