// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataEntities
{
    public partial class TblPromocion
    {
        public TblPromocion()
        {
            TblVentas = new HashSet<TblVentas>();
        }

        public int IdPromocion { get; set; }
        public string NombrePromocion { get; set; }
        public string Descripcion { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public decimal? Descuento { get; set; }

        public virtual ICollection<TblVentas> TblVentas { get; set; }
    }
}