// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataEntities
{
    public partial class TblTipoMovimiento
    {
        public TblTipoMovimiento()
        {
            TblMovimientoProductos = new HashSet<TblMovimientoProductos>();
            TblProductoDañado = new HashSet<TblProductoDañado>();
        }

        public int IdTipoMovimiento { get; set; }
        public string NombreMovimiento { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<TblMovimientoProductos> TblMovimientoProductos { get; set; }
        public virtual ICollection<TblProductoDañado> TblProductoDañado { get; set; }
    }
}